# Generated by Django 6.0.3 on 2026-03-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='recorrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receita',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='recorrente',
            field=models.BooleanField(default=False),
        ),
    ]
