# Generated by Django 6.0.3 on 2026-04-05 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='data_fim',
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.categoria'),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
