# Generated by Django 6.0.3 on 2026-04-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_despesa_criado_em_receita_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
